name: interaction-share-260908
source:
  format: named-npz-v1
  archive: /g/data/ql44/we2614/interaction_share_260908/views.npz
  sha256: cde6c9c2a6896d8bb7e406dd56216564375bb249362794967a71bb17307143fb
  axis_order:
  - observation
  - process
base_output_dir: /g/data/ql44/we2614/interaction_share_260908/mpis
pyspi_config: configs/pyspi/benchmarked_p90.yaml
normalise: false
random_seed: 260908
