base_output_dir: data/r_rho_mi_spec_l-0/
pyspi_config: configs/pyspi/cases/r_rho_mi.yaml
pyspi_subset: default
normalise: false
rng_seed: 42
save_heatmap: false
threads: 4
defaults:
  M_values:
  - 16
  T_values:
  - 100
  instances: 30
mts_classes:
- name: fixed_l-0_m-16_nm-0
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 16
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-15_nm-1
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 15
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-14_nm-2
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 14
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-13_nm-3
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 13
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-12_nm-4
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 12
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-11_nm-5
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 11
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-10_nm-6
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 10
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-9_nm-7
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 9
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-8_nm-8
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 8
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-7_nm-9
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 7
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-6_nm-10
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 6
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-5_nm-11
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 5
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-4_nm-12
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 4
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-3_nm-13
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 3
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-2_nm-14
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 2
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-1_nm-15
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 1
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_l-0_m-0_nm-16
  labels:
  - sinusoidal-mother
  - fixed
  generator: sin_mts_mother
  base_params:
    regime: fixed
    n_linear: 0
    n_monotonic: 0
    noise_std: 0.02
    ar1_a: 0.8
    ar1_noise_std: 1.0
    zscore: false
