.statistics.basic:
  # Covariance
  Covariance:
    labels:
      - undirected
      - linear
      - signed
      - multivariate
      - contemporaneous
    dependencies:
    configs:
      - estimator: EmpiricalCovariance

  # Spearman's correlation coefficient
  SpearmanR:
    labels:
      - undirected
      - nonlinear
      - signed
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - squared: False

  # Kendall's rank correlation coefficient
  KendallTau:
    labels:
      - undirected
      - nonlinear
      - signed
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - squared: False

.statistics.distance:
  PairwiseDistance:
    labels:
      - unsigned
      - unordered
      - nonlinear
      - undirected
    dependencies:
    configs:
      - metric: "euclidean"
      - metric: "cityblock"
      - metric: "cosine"
      - metric: "chebyshev"
      - metric: "canberra"
      - metric: "braycurtis"

  # Distance correlation
  DistanceCorrelation:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - contemporaneous
    dependencies:
    configs:
      - biased: False
      - biased: True

  DynamicTimeWarping:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - global_constraint: null
      - global_constraint: itakura
      - global_constraint: sakoe_chiba

    
.statistics.infotheory:
  MutualInfo:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - contemporaneous
    dependencies: 
      - java
    configs:
      - estimator: gaussian

      - estimator: kraskov
        prop_k: 4

      - estimator: kraskov
        prop_k: 4
        dyn_corr_excl: AUTO

      - estimator: kernel
        kernel_width: 0.25


.statistics.spectral:
  # Coherence (ordinal or squared? imaginary components of the coherence)
  ImaginaryCoherence:
    labels:
      - undirected
      - linear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fs: 1

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5

      - fs: 1
        statistic: max

      - fmin: 0
        fmax: 0.25
        statistic: max

      - fmin: 0.25
        fmax: 0.5
        statistic: max

  PhaseSlopeIndex:
    labels:
      - directed
      - linear/nonlinear
      - unsigned
      - bivariate
      - frequency-dependent
    dependencies:
    configs:
      - fmin: 0
        fmax: 0.5

      - fmin: 0
        fmax: 0.25

      - fmin: 0.25
        fmax: 0.5