base_output_dir: data/order_parameter/spin_order_smoke
timestamp: false
pyspi_config: configs/pyspi/benchmarked_p90.yaml
normalise: false
rng_seed: 438109
save_heatmap: false
threads: 1
defaults:
  M_values: [20]
  T_values: [100]
  instances: 1
mts_classes:
  - name: miller-huse-smoke
    labels: [miller-huse, order-parameter, smoke]
    generator: miller_huse
    base_params:
      coupling: 0.22
      mu: 3.0
      lattice_side: 16
      transients: 100
      future_truth_T: 100
      patch_shape: [4, 5]
      store_full_field: false
