base_output_dir: data/r_rho_mi/20260305_smooth-2/
timestamp: false
pyspi_config: configs/pyspi/cases/r_rho_mi.yaml
pyspi_subset: default
normalise: false
rng_seed: 42
save_heatmap: false
threads: 4

defaults:
  M_values: [16]
  T_values: [500]
  instances: 30

mts_classes:
- name: "smooth_A-pi8"
  labels: [sinusoidal-mother, smooth]
  generator: "sin_mts_smooth"
  base_params:
    A: 0.3927  # pi/8
    noise_std: 0.1
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: true

- name: "smooth_A-pi2"
  labels: [sinusoidal-mother, smooth]
  generator: "sin_mts_smooth"
  base_params:
    A: 1.5708  # pi/2
    noise_std: 0.1
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: true

- name: "smooth_A-pi" 
  labels: [sinusoidal-mother, smooth]
  generator: "sin_mts_smooth"
  base_params:
    A: 20  # pi
    noise_std: 0.1
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: true
