base_output_dir: data/r_rho_mi/260318_g-tanhsin_k-20/
timestamp: false
pyspi_config: configs/pyspi-v2/cases/r_rho_mi.yaml
pyspi_subset: default
normalise: false
rng_seed: 42
save_heatmap: false
threads: 4

defaults:
  M_values: [20]
  T_values: [1000]
  instances: 30

mts_classes:
- name: "smooth_A-pi32"
  labels: [sinusoidal-mother, smooth]
  generator: "sin_mts_smooth"
  base_params:
    A: 0.09812  # pi/32
    k: 20 # 2*pi
    linspace: true
    noise_std: 0.1
    noise_std_variable: true
    noise_std_scale: 2  #e=2.718
    ar1_a: 0.99
    ar1_noise_std: 1.0
    zscore: true

- name: "smooth_A-pi2"
  labels: [sinusoidal-mother, smooth]
  generator: "sin_mts_smooth"
  base_params:
    A: 1.5708  # pi/2
    k: 20  # 2*pi
    linspace: true
    noise_std: 0.1
    noise_std_variable: true
    noise_std_scale: 2  #e=2.718
    ar1_a: 0.99
    ar1_noise_std: 1.0
    zscore: true

- name: "smooth_A-8pi"
  labels: [sinusoidal-mother, smooth]
  generator: "sin_mts_smooth"
  base_params:
    A: 12.5663  # 4*pi
    # A: 25.1327  # 8*pi 
    # k: 20  # 2*pi
    linspace: true
    noise_std: 0.1
    noise_std_variable: true
    noise_std_scale: 2  #e=2.718
    ar1_a: 0.99
    ar1_noise_std: 1.0
    zscore: true
