.statistics.distance:
  PairwiseDistance:
    labels:
      - unsigned
      - unordered
      - nonlinear
      - undirected
    dependencies:
    configs:
      - metric: "euclidean"

  CrossPairwiseDistance:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - temporal
    dependencies:
    configs:
      # tau=4 matches lagged_A-5 (linspace 0..4 over M=16 channels)
      - metric: "euclidean"
        tau: 10
        statistic: "min"
      # tau=15 matches lagged_A-16 (linspace 0..15 over M=16 channels)
      # - metric: "euclidean"
      #   tau: 15
      #   statistic: "min"

  DynamicTimeWarping:
    labels:
      - undirected
      - nonlinear
      - unsigned
      - bivariate
      - time-dependent
    dependencies:
    configs:
      - global_constraint: null
