base_output_dir: data/case_iv_var_var/
pyspi_config: configs/pyspi/cases/case_iv_var_var.yaml

pyspi_subset: default
normalise: false
rng_seed: 110305
save_heatmap: false
threads: 16

defaults:
  M_values: [8, 16]
  T_values: [400, 800, 1600, 3200]
  instances: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

mts_classes:
  - name: "VAR-1_phi-0.1_coupling-0.9_noise-0.1"
    labels: ["linear", "gaussian", "var", "ring_unidirectional"]
    generator: "varma"
    include_base_variant: true
    base_params:
      phi: 0.1
      coupling: 0.9
      topology: "ring-unidirectional"
      ma_phi: 0.0
      ma_coupling: 0.0
      noise_std: 0.1
      transients: 500
      zscore: true
      target_rho: 0.98
    variants:

  - name: "VAR-1_phi-0.9_coupling-0.1_noise-3.0"
    labels: ["linear", "gaussian", "var", "ring_unidirectional"]
    generator: "varma"
    include_base_variant: true
    base_params:
      phi: 0.9
      coupling: 0.1
      topology: "ring-unidirectional"
      ma_phi: 0.0
      ma_coupling: 0.0
      noise_std: 3.0
      transients: 500
      zscore: true
      target_rho: 0.98
    variants:

