base_output_dir: data/test/blended_config
pyspi_config: configs/pyspi-v2/blended_config.yaml
normalise: false
rng_seed: 110305
save_heatmap: false
threads: 1
timestamp: false

defaults:
  M_values: [5,10,20,30]
  T_values: [100,500,1000,2000]
  instances: 1

mts_classes:
  - name: "VAR(1)-AllToAll"
    labels: ["linear", "gaussian", "var", "undirected"]
    generator: "varma"
    base_params:
      phi: 0.8
      coupling: 0.6
      topology: "all-to-all"
      ma_phi: 0.0
      ma_coupling: 0.0
      noise_std: 0.2
      transients: 500
      zscore: true
      target_rho: 0.99

  - name: "GaussianNoise"
    labels: ["noise", "gaussian"]
    generator: "gaussian_noise"
    base_params:
      zscore: true

  - name: "CauchyNoise"
    labels: ["noise", "cauchy", "heavy-tail"]
    generator: "cauchy_noise"
    base_params:
      zscore: false

  - name: "CML-Logistic"
    labels: ["nonlinear", "chaotic", "cml"]
    generator: "cml_logistic"
    base_params:
      alpha: 1.7522
      eps: 0.00115
      transients: 500
      sample_every: 12
      zscore: false

  - name: "Kuramoto-Ring"
    labels: ["nonlinear", "oscillator", "kuramoto", "undirected"]
    generator: "kuramoto"
    base_params:
      connectivity: "ring"
      K: -4
      k_ring: 1
      dt: 0.002
      omega_mean: 0.6283185307179586
      omega_std: 0.01
      eta: 0.0
      transients: 2000
      output: "sin"
      zscore: true
