.statistics.basic:
  Covariance:
    labels:
    - undirected
    - linear
    - signed
    - multivariate
    - contemporaneous
    dependencies: null
    configs:
    - estimator: EmpiricalCovariance
    - estimator: EllipticEnvelope
    - estimator: GraphicalLasso
    - estimator: GraphicalLassoCV
    - estimator: LedoitWolf
    - estimator: MinCovDet
    - estimator: OAS
    - estimator: ShrunkCovariance
    - estimator: EmpiricalCovariance
      squared: true
    - estimator: EllipticEnvelope
      squared: true
    - estimator: GraphicalLasso
      squared: true
    - estimator: LedoitWolf
      squared: true
    - estimator: MinCovDet
      squared: true
    - estimator: OAS
      squared: true
    - estimator: ShrunkCovariance
      squared: true
  Precision:
    labels:
    - undirected
    - linear
    - signed
    - multivariate
    - contemporaneous
    dependencies: null
    configs:
    - estimator: EmpiricalCovariance
    - estimator: EllipticEnvelope
    - estimator: GraphicalLasso
    - estimator: GraphicalLassoCV
    - estimator: LedoitWolf
    - estimator: MinCovDet
    - estimator: OAS
    - estimator: ShrunkCovariance
    - estimator: EmpiricalCovariance
      squared: true
    - estimator: EllipticEnvelope
      squared: true
    - estimator: GraphicalLasso
      squared: true
    - estimator: GraphicalLassoCV
      squared: true
    - estimator: LedoitWolf
      squared: true
    - estimator: MinCovDet
      squared: true
    - estimator: OAS
      squared: true
    - estimator: ShrunkCovariance
      squared: true
  SpearmanR:
    labels:
    - undirected
    - nonlinear
    - signed
    - bivariate
    - contemporaneous
    dependencies: null
    configs:
    - squared: true
    - squared: false
  KendallTau:
    labels:
    - undirected
    - nonlinear
    - signed
    - bivariate
    - contemporaneous
    dependencies: null
    configs:
    - squared: true
    - squared: false
  CrossCorrelation:
    labels:
    - undirected
    - linear
    - signed/unsigned
    - bivariate
    - time-dependent
    dependencies: null
    configs:
    - statistic: max
    - statistic: max
      squared: true
    - statistic: mean
    - statistic: mean
      squared: true
    - statistic: mean
      sigonly: false
    - statistic: mean
      squared: true
      sigonly: false
