.statistics.distance:
  PairwiseDistance:
    labels:
    - unsigned
    - unordered
    - nonlinear
    - undirected
    dependencies: null
    configs:
    - metric: euclidean
    - metric: cityblock
    - metric: cosine
    - metric: chebyshev
    - metric: canberra
    - metric: braycurtis
  CrossPairwiseDistance:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - temporal
    dependencies: null
    configs:
    - metric: euclidean
      tau: 10
      statistic: min
  DistanceCorrelation:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - contemporaneous
    dependencies: null
    configs:
    - biased: false
    - biased: true
  MultiscaleGraphCorrelation:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - contemporaneous
    dependencies: null
    configs: null
  HilbertSchmidtIndependenceCriterion:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - contemporaneous
    dependencies: null
    configs:
    - biased: false
    - biased: true
  HellerHellerGorfine:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - contemporaneous
    dependencies: null
    configs: null
  CrossDistanceCorrelation:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - time-dependent
    dependencies: null
    configs:
    - max_lag: 1
    - max_lag: 10
  CrossMultiscaleGraphCorrelation:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - time-dependent
    dependencies: null
    configs:
    - max_lag: 1
    - max_lag: 10
  Barycenter:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - time-dependent
    dependencies: null
    configs:
    - mode: euclidean
      statistic: mean
    - mode: euclidean
      statistic: max
    - mode: dtw
      statistic: mean
    - mode: dtw
      statistic: max
    - mode: euclidean
      statistic: mean
      squared: true
    - mode: euclidean
      statistic: max
      squared: true
    - mode: dtw
      statistic: mean
      squared: true
    - mode: dtw
      statistic: max
      squared: true
  GromovWasserstainTau:
    labels:
    - unsigned
    - distance
    - unordered
    - nonlinear
    - undirected
    dependencies: null
    configs: null
  DynamicTimeWarping:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - time-dependent
    dependencies: null
    configs:
    - global_constraint: null
    - global_constraint: itakura
    - global_constraint: sakoe_chiba
  SoftDynamicTimeWarping:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - time-dependent
    dependencies: null
    configs:
    - global_constraint: null
    - global_constraint: itakura
    - global_constraint: sakoe_chiba
  LongestCommonSubsequence:
    labels:
    - undirected
    - nonlinear
    - unsigned
    - bivariate
    - time-dependent
    dependencies: null
    configs:
    - global_constraint: null
    - global_constraint: itakura
    - global_constraint: sakoe_chiba
