base_output_dir: data/dtw_euclidean_1.2/
pyspi_config: configs/pyspi-v2/cases/dtw_euclidean.yaml
pyspi_subset: default
normalise: false
rng_seed: 42
save_heatmap: false
threads: 4

defaults:
  M_values: [16]
  T_values: [100]
  instances: 100

mts_classes:
  - name: "fixed-mother-1.2"
    labels: ["warping", "fixed", "rebound"]
    generator: "warping_mts"
    base_params:
      warping_channel_regime: "fixed"
      n_noisy: 16 
      n_warped: 0
      warping_path_regime: "rebound"
      warp_p: 0.1
      warp_p_step: 0.9
      noise_std: 0.1
      noise_std_variable: false
      ar1_a: 0.8
      ar1_noise_std: 1.0
      zscore: false

  - name: "fixed-warped-1.2"
    labels: ["warping", "fixed", "rebound"]
    generator: "warping_mts"
    base_params:
      warping_channel_regime: "fixed"
      n_noisy: 0
      n_warped: 16
      warping_path_regime: "rebound"
      warp_p: 0.1
      warp_p_step: 0.9
      noise_std: 0.1
      noise_std_variable: false
      ar1_a: 0.8
      ar1_noise_std: 1.0
      zscore: false

  - name: "random-mixed-1.2"
    labels: ["warping", "random", "rebound"]
    generator: "warping_mts"
    base_params:
      warping_channel_regime: "random"
      warping_path_regime: "rebound"
      warp_p: 0.1
      warp_p_step: 0.9
      noise_std: 0.1
      noise_std_variable: false
      ar1_a: 0.8
      ar1_noise_std: 1.0
      zscore: false
