base_output_dir: data/dtw_euclidean/dtw_euclidean_vary-pstep/
pyspi_config: configs/pyspi/cases/dtw_euclidean.yaml
pyspi_subset: default
normalise: false
rng_seed: 42
save_heatmap: false
threads: 4
defaults:
  M_values:
  - 16
  T_values:
  - 100
  instances: 30
mts_classes:
- name: fixed_w-16_pstep-0.0
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.0
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.05
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.05
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.11
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.11
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.16
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.16
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.21
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.21
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.26
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.26
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.32
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.32
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.37
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.37
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.42
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.42
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.47
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.47
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.53
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.53
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.58
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.58
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.63
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.63
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.68
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.68
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.74
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.74
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.79
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.79
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.84
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.84
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.89
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.89
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-0.95
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 0.95
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
- name: fixed_w-16_pstep-1.0
  labels:
  - warped
  - fixed
  generator: warping_mts
  base_params:
    warping_channel_regime: fixed
    n_noisy: 0
    n_warped: 16
    warping_path_regime: rebound
    warp_p: 0.9
    warp_p_step: 1.0
    noise_std: 0.05
    ar1_a: 0.95
    ar1_noise_std: 1.0
    zscore: false
