"""
Generic UEA dataset preprocessor.

Downloads any UEA multivariate time series classification dataset via aeon,
combines train + test splits, z-scores per channel, and writes per-trial
timeseries.npy files into the directory layout expected by run_experiments.py.

Also writes a ready-to-use YAML experiment config when --config-out is given.

Usage (run once per dataset, from project root):

    python -m src.prep_uea \\
        --dataset BasicMotions \\
        --output-dir data/basicmotions \\
        --config-out configs/generate/basicmotions.yaml

    # Then submit (use total jobs printed above):
    qsub -J 1-<TOTAL> -v DATASET=basicmotions jobs/physics/run_uea.pbs

Output layout (mirrors run_experiments.py real-data paths):

    <output-dir>/
        <cls_slug>/class<cls_slug>_I{n}/timeseries.npy
        ...

Each timeseries.npy is float32, shape (T, M), z-scored per channel.
Existing files are skipped (safe to re-run after partial failures).
"""

import argparse
from pathlib import Path

import numpy as np
from scipy.stats import zscore

from .utils import class_dir_name, slugify


def _load_all_trials(dataset: str):
    try:
        from aeon.datasets import load_classification
    except ImportError as exc:
        raise SystemExit("aeon is required: uv pip install -e '.[real]'") from exc

    print(f"[INFO] Downloading {dataset} train split …")
    X_tr, y_tr = load_classification(dataset, split="train")
    print(f"[INFO] Downloading {dataset} test split …")
    X_te, y_te = load_classification(dataset, split="test")

    X_all = np.concatenate([X_tr, X_te], axis=0).astype(float)
    y_all = np.concatenate([np.asarray(y_tr), np.asarray(y_te)]).astype(str)
    N, M, T = X_all.shape
    print(f"[INFO] Combined: {N} trials  M={M} channels  T={T} timepoints")
    return X_all, y_all


def _write_trials(X_all: np.ndarray, y_all: np.ndarray, out_root: Path) -> dict:
    """
    Write per-trial timeseries.npy files.

    Returns dict: cls_label -> (cls_slug, cls_name, n_instances)
    """
    class_labels = sorted(set(y_all.tolist()))
    summary = {}

    for cls_label in class_labels:
        mask = np.where(y_all == cls_label)[0]
        ordered = sorted(mask.tolist())  # deterministic: sorted by original index

        cls_slug = slugify(cls_label)
        cls_name = cls_slug  # directory name = slugified label
        class_dir = out_root / class_dir_name(cls_name)

        written = skipped = 0
        for instance, trial_idx in enumerate(ordered):
            dest = class_dir / f"class{cls_slug}_I{instance}"
            ts_path = dest / "timeseries.npy"
            if ts_path.exists():
                skipped += 1
                continue

            sample = X_all[trial_idx]  # (M, T) channels-first from aeon
            data = sample.T            # (T, M)
            data = zscore(data, axis=0, nan_policy="omit")
            data = np.nan_to_num(data, nan=0.0, posinf=0.0, neginf=0.0)
            data = data.astype(np.float32)

            dest.mkdir(parents=True, exist_ok=True)
            np.save(ts_path, data)
            written += 1

        print(
            f"[INFO]   '{cls_label}' ({cls_slug}): "
            f"{len(ordered)} trials  written={written}  skipped={skipped}"
        )
        summary[cls_label] = (cls_slug, cls_name, len(ordered))

    return summary


def _write_yaml_config(
    dataset: str,
    out_root: Path,
    summary: dict,
    pyspi_config: str,
    threads: int,
    rng_seed: int,
    config_out: Path,
) -> int:
    """Write experiment YAML config. Returns total job count."""
    lines = [
        f"base_output_dir: {out_root}/",
        "timestamp: false",
        f"pyspi_config: {pyspi_config}",
        "normalise: false",
        f"rng_seed: {rng_seed}",
        "save_heatmap: false",
        f"threads: {threads}",
        "",
        f"# {dataset}: auto-generated by src/prep_uea.py",
        "# M/T not set — determined from loaded arrays at runtime.",
        "mts_classes:",
    ]

    for cls_label, (cls_slug, cls_name, n_instances) in summary.items():
        lines += [
            f'  - name: "{cls_name}"',
            f'    labels: ["{slugify(dataset)}", "{cls_slug}"]',
            '    package: "aeon"',
            f'    dataset_name: "{dataset}"',
            f'    classes: ["{cls_label}"]',
            "    zscore: false  # already z-scored by prep_uea.py",
            f"    instances: {n_instances}",
            "",
        ]

    config_out.parent.mkdir(parents=True, exist_ok=True)
    config_out.write_text("\n".join(lines) + "\n")

    total = sum(n for _, _, n in summary.values())
    return total


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", required=True, help="UEA dataset name (case-sensitive)")
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument(
        "--config-out",
        type=Path,
        default=None,
        help="Path to write the YAML experiment config (optional)",
    )
    parser.add_argument(
        "--pyspi-config",
        default="configs/pyspi/cases/eeml.yaml",
        help="pyspi config to embed in the generated YAML",
    )
    parser.add_argument("--threads", type=int, default=4)
    parser.add_argument("--rng-seed", type=int, default=110305)
    args = parser.parse_args()

    X_all, y_all = _load_all_trials(args.dataset)
    summary = _write_trials(X_all, y_all, args.output_dir)

    if args.config_out:
        total = _write_yaml_config(
            dataset=args.dataset,
            out_root=args.output_dir,
            summary=summary,
            pyspi_config=args.pyspi_config,
            threads=args.threads,
            rng_seed=args.rng_seed,
            config_out=args.config_out,
        )
        stem = args.config_out.stem
        print(f"[INFO] Config written → {args.config_out}")
        print(f"[INFO] Total PBS jobs : {total}")
        print(f"[INFO] Submit with   : qsub -J 1-{total} -v DATASET={stem} jobs/physics/run_uea.pbs")
    else:
        total = sum(n for _, _, n in summary.values())
        print(f"[INFO] Total trials  : {total}  (pass --config-out to generate YAML)")

    print("[INFO] Done.")


if __name__ == "__main__":
    main()
