#!/bin/bash
# Submit the CML physical-diagnostic scout in batches compatible with Gadi's
# max_array_size=10. This prepares physical targets before any confirmatory SPI
# embedding is fitted.

set -euo pipefail

ALPHAS="${ALPHAS:-1.60:2.00:0.01}"
EPS_VALUES="${EPS_VALUES:-0.3}"
LATTICE_SIZES="${LATTICE_SIZES:-128;256}"
INSTANCES="${INSTANCES:-16}"
CHUNK_SIZE="${CHUNK_SIZE:-120}"
SUBJOBS_PER_ARRAY="${SUBJOBS_PER_ARRAY:-10}"
CONCURRENT_TASKS="${CONCURRENT_TASKS:-48}"
TRANSIENTS="${TRANSIENTS:-65536}"
RECORD_STEPS="${RECORD_STEPS:-16384}"
ANALYSIS_PREFIXES="${ANALYSIS_PREFIXES:-2048;8192;16384}"
STATIONARITY_BLOCKS="${STATIONARITY_BLOCKS:-4}"
SELECTED_SPATIAL_BAND="${SELECTED_SPATIAL_BAND:-0.25:0.45}"
PATTERN_WORD_LENGTH="${PATTERN_WORD_LENGTH:-4}"
LYAPUNOV_STEPS="${LYAPUNOV_STEPS:-4096}"
OUTPUT_DIR="${OUTPUT_DIR:-results/cml-order-parameter-discovery}"
PBS_SCRIPT="${PBS_SCRIPT:-jobs/gadi/run_cml_order_parameter_scout.pbs}"

TOTAL_TASKS=$(python scripts/cml_order_parameter_scout.py \
    --alphas "$ALPHAS" \
    --eps "$EPS_VALUES" \
    --lattice-sizes "$LATTICE_SIZES" \
    --instances "$INSTANCES" \
    --list)

BATCH_TASKS=$(( CHUNK_SIZE * SUBJOBS_PER_ARRAY ))
N_BATCHES=$(( (TOTAL_TASKS + BATCH_TASKS - 1) / BATCH_TASKS ))

echo "[INFO] total=$TOTAL_TASKS chunk=$CHUNK_SIZE subjobs/array=$SUBJOBS_PER_ARRAY batches=$N_BATCHES"
echo "[INFO] alpha=$ALPHAS eps=$EPS_VALUES L=$LATTICE_SIZES instances=$INSTANCES"

for (( batch=0; batch<N_BATCHES; batch++ )); do
    OFFSET=$(( batch * BATCH_TASKS ))
    qsub \
        -J "1-${SUBJOBS_PER_ARRAY}" \
        -v "TOTAL_TASKS=${TOTAL_TASKS},CHUNK_SIZE=${CHUNK_SIZE},BATCH_OFFSET=${OFFSET},CONCURRENT_TASKS=${CONCURRENT_TASKS},ALPHAS=${ALPHAS},EPS_VALUES=${EPS_VALUES},LATTICE_SIZES=${LATTICE_SIZES},INSTANCES=${INSTANCES},TRANSIENTS=${TRANSIENTS},RECORD_STEPS=${RECORD_STEPS},ANALYSIS_PREFIXES=${ANALYSIS_PREFIXES},STATIONARITY_BLOCKS=${STATIONARITY_BLOCKS},SELECTED_SPATIAL_BAND=${SELECTED_SPATIAL_BAND},PATTERN_WORD_LENGTH=${PATTERN_WORD_LENGTH},LYAPUNOV_STEPS=${LYAPUNOV_STEPS},OUTPUT_DIR=${OUTPUT_DIR}" \
        "$PBS_SCRIPT"
done

echo "[INFO] submitted $N_BATCHES array jobs"
